version: '3.3'
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - 5422:5432
    environment:
      - POSTGRES_DB=cash-service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin